# Strings Manipulation

In [1]:
# strings in python
string1 = 'Dhiraj'
print(string1)

Dhiraj

In [3]:
print(string1[0])
string1 = 'Upadhaya'
print(string1)

U
Upadhaya

In [6]:
# --------------------
# 1. Creating strings
# --------------------
print('1. Creating Strings')
s1 = "Hello"
s2 = 'World'
s3 = """This is a multiline string
Second line"""
print(s1)
print(s2)
print(s3)

1. Creating Strings
Hello
World
This is a multiline string
Second line

In [7]:
# 2. String concatenation
print("\n2. Concatenation")
full = s1 + " " + s2
print("Concatenated:", full)

2. Concatenation
Concatenated: Hello World

In [2]:
# 3. repetition
repeat ="hi how are you? " * 5
print(repeat, end="end of string")

hi how are you? hi how are you? hi how are you? hi how are you? hi how are you? end of string

In [15]:
# 4. indexing
text = "python is green and mean"
print("string: ", text)
print("First character: ", text[0])
print("Last character: ", text[-1])
print("Third character: ", text[2])
print("First 2 characters: ", text[:2])
print("print until last 3 character: ", text[:-3])
print("print every second character: ", text[::2])
print("inverting the string (from last to first): ", text[::-1])
print("inverted string but every second char: ", text[::-2])

# whatever you can do with lists can be done with strings

string:  python is green and mean
First character:  p
Last character:  n
Third character:  t
First 2 characters:  py
print until last 3 character:  python is green and m
print every second character:  pto sgenadma
inverting the string (from last to first):  naem dna neerg si nohtyp
inverted string but every second char:  ne n er inhy

### Escape characters
escape characters are strings like '\n' that encode special characters
\'	    Single Quote	

\"	    Double Quote

\\	    Backslash	

\n	    New Line	

\r	    Carriage Return	

\t	    Tab	

\b	    Backspace	

\f	    Form Feed	

\ooo	Octal value	

\xhh	Hex value

In [ ]:
# 6. string methods
name = 'DATA science'
print('original', name)
print('upper: ', name.upper())
print('lower: ', name.lower())
print('strip spaces: ', name.strip())
print('replace: ', name.replace("science", "analysis"))

original DATA science
upper:  DATA SCIENCE
lower:  data science
strip spaces:  DATA science
replace:  DATA analysis

In [3]:
# 7. checking content
sample = 'Python123'
print("is it alphabet: ", sample.isalpha())
print("is it digit: ", sample.isdigit())
print("is it alphanumeric: ", sample.isalnum())

is it alphabet:  False
is it digit:  False
is it alphanumeric:  True

In [7]:
# 8. splitting/joining
sentence = "python is easy to learn"
print('the sentence is ', sentence)
words = sentence.split(' ')
print(words)
joined = '*'.join(words)
print("Joined: ", joined)

the sentence is  python is easy to learn
['python', 'is', 'easy', 'to', 'learn']
Joined:  python*is*easy*to*learn

In [9]:
# 9. formatting
name = "Taheera"
age = 25
gender = 'F'
# old format
print('My name is %s and I am %d years old, and my gender is %s' % (name, age, gender))
# format()
print('My name is {} and I am {} years old, and my gender is {}'.format(name, age, gender))
# f-string
print(f'My name is {name} and I am {age} years old, and my gender is {gender}')

My name is Taheera and I am 25 years old, and my gender is F
My name is Taheera and I am 25 years old, and my gender is F
My name is Taheera and I am 25 years old, and my gender is F

In [10]:
# strings are immutable
text = "hello"
text = 'H' + text[1:]
print("modified: ", text)

modified:  Hello

# More (using dataframes)

In [12]:
import pandas as pd
from pydataset import data

In [13]:
# Create mtcars dataset with car names
data = {
    "car_name": [ "Mazda RX4", "Mazda RX4    Wag", "Datsun 710","Hornet 4 Drive", "Hornet   Sportabout  ", "Valiant", "Duster 360", "merc 240D", "Merc 230", "Merc 280" ],
    "mpg": [21.0, 21.0, 22.8, 21.4, 18.7, 18.1, 14.3, 24.4, 22.8, 19.2]}
df = pd.DataFrame(data)
print("Original Data:\n", df)

Original Data:
                 car_name   mpg
0              Mazda RX4  21.0
1       Mazda RX4    Wag  21.0
2             Datsun 710  22.8
3         Hornet 4 Drive  21.4
4  Hornet   Sportabout    18.7
5                Valiant  18.1
6             Duster 360  14.3
7              merc 240D  24.4
8               Merc 230  22.8
9               Merc 280  19.2

In [17]:
# Search
mazda_cars = df[df['car_name'].str.contains("Mazda")]
print("Mazda cars: \n")
mazda_cars

Mazda cars:

           car_name   mpg
0         Mazda RX4  21.0
1  Mazda RX4    Wag  21.0

In [ ]:
# showing case parameter to switch case sensitivity
df[df['car_name'].str.contains("Merc", case=True)]

   car_name   mpg
8  Merc 230  22.8
9  Merc 280  19.2

In [20]:
df[df['car_name'].str.contains("merc", case=False)]

    car_name   mpg
7  merc 240D  24.4
8   Merc 230  22.8
9   Merc 280  19.2

In [ ]:
# cars starting with merc
merc_cars = df[df['car_name'].str.startswith("Merc")]
print("Cars starting with 'Merc':\n", merc_cars)

Cars starting with 'Merc':
    car_name   mpg
8  Merc 230  22.8
9  Merc 280  19.2

In [ ]:
# here you can also put a tuple (only accepts tuple (no lists))
df[df['car_name'].str.startswith(('merc', 'Merc'))]

    car_name   mpg
7  merc 240D  24.4
8   Merc 230  22.8
9   Merc 280  19.2

In [28]:
df[df['car_name'].str.endswith('Drive')]

         car_name   mpg
3  Hornet 4 Drive  21.4

In [30]:
# Replace strings
# making new column for edited names
df['car_name_updated'] = df['car_name'].str.replace('Merc', 'Mercedes', regex=False)
print("Updated Names:\n", df[['car_name', 'car_name_updated']])

Updated Names:
                 car_name       car_name_updated
0              Mazda RX4              Mazda RX4
1       Mazda RX4    Wag       Mazda RX4    Wag
2             Datsun 710             Datsun 710
3         Hornet 4 Drive         Hornet 4 Drive
4  Hornet   Sportabout    Hornet   Sportabout
5                Valiant                Valiant
6             Duster 360             Duster 360
7              merc 240D              merc 240D
8               Merc 230           Mercedes 230
9               Merc 280           Mercedes 280

In [32]:
# putting 'case=False'
df['car_name_updated'] = df['car_name'].str.replace('Merc', 'Mercedes', case=False, regex=False)
print("Updated Names:\n", df[['car_name', 'car_name_updated']])

Updated Names:
                 car_name       car_name_updated
0              Mazda RX4              Mazda RX4
1       Mazda RX4    Wag       Mazda RX4    Wag
2             Datsun 710             Datsun 710
3         Hornet 4 Drive         Hornet 4 Drive
4  Hornet   Sportabout    Hornet   Sportabout
5                Valiant                Valiant
6             Duster 360             Duster 360
7              merc 240D          Mercedes 240D
8               Merc 230           Mercedes 230
9               Merc 280           Mercedes 280

In [34]:
# splitting brand names to extract categories, useful for feature engineering
df['brand'] = df['car_name'].str.split().str[0]
print("Extracted Brand:\n", df[['car_name', 'brand']])

Extracted Brand:
                 car_name    brand
0              Mazda RX4    Mazda
1       Mazda RX4    Wag    Mazda
2             Datsun 710   Datsun
3         Hornet 4 Drive   Hornet
4  Hornet   Sportabout     Hornet
5                Valiant  Valiant
6             Duster 360   Duster
7              merc 240D     merc
8               Merc 230     Merc
9               Merc 280     Merc

In [35]:
df['upper_name'] = df['car_name'].str.upper()
df['lower_name'] = df['car_name'].str.lower()
df

                car_name   mpg  ...             upper_name             lower_name
0              Mazda RX4  21.0  ...              MAZDA RX4              mazda rx4
1       Mazda RX4    Wag  21.0  ...       MAZDA RX4    WAG       mazda rx4    wag
2             Datsun 710  22.8  ...             DATSUN 710             datsun 710
3         Hornet 4 Drive  21.4  ...         HORNET 4 DRIVE         hornet 4 drive
4  Hornet   Sportabout    18.7  ...  HORNET   SPORTABOUT    hornet   sportabout
5                Valiant  18.1  ...                VALIANT                valiant
6             Duster 360  14.3  ...             DUSTER 360             duster 360
7              merc 240D  24.4  ...              MERC 240D              merc 240d
8               Merc 230  22.8  ...               MERC 230               merc 230
9               Merc 280  19.2  ...               MERC 280               merc 280

[10 rows x 6 columns]

In [ ]:
# clean names by trimming spaces
df['clean_name'] = df['car_name'].str.strip()
print("Clean names:\n", df[['car_name', 'clean_name']])