In [2]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

In [3]:
#Create Data
rawdata = [
    [1, 'Taheera', 70, 86],
    [2, 'Aelita', 56, 90],
    [3, 'Khulan', 87, 90],
    [4, 'Batgerel', 71, 79],
    [5, 'Manisha', 88, 76],
]

df = pd.DataFrame(rawdata, columns=['Rollno','Name', 'Maths', 'English'])
df.head()

   Rollno      Name  Maths  English
0       1   Taheera     70       86
1       2    Aelita     56       90
2       3    Khulan     87       90
3       4  Batgerel     71       79
4       5   Manisha     88       76

# Wide to Long

In [4]:
df_long = pd.melt(df, id_vars=['Name'], value_vars=['Maths', 'English'], var_name='Subject', value_name='Marks')
df_long

       Name  Subject  Marks
0   Taheera    Maths     70
1    Aelita    Maths     56
2    Khulan    Maths     87
3  Batgerel    Maths     71
4   Manisha    Maths     88
5   Taheera  English     86
6    Aelita  English     90
7    Khulan  English     90
8  Batgerel  English     79
9   Manisha  English     76

In [5]:
df_long.groupby('Subject')['Marks'].agg(['sum', 'mean', 'count'])

         sum  mean  count
Subject
English  421  84.2      5
Maths    372  74.4      5

In [6]:
# df['Maths', 'English'].mean()
df[['Maths', 'English']].mean()

Maths      74.4
English    84.2
dtype: float64

In [7]:
df['Maths'].mean()

np.float64(74.4)

## April 19
- Data Frame
- Long to Wide
- Wide to Long
- group by summary
- missing values - insert, find count of missing values, [Imputing](https://www.merriam-webster.com/dictionary/impute) Value
- Merge 2 data frame

In [9]:
df.dtypes

Rollno      int64
Name       object
Maths       int64
English     int64
dtype: object