In [27]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

In [28]:
from pydataset import data
mtcars = data('mtcars')
mtcars_copy = mtcars.copy()
mtcars.head(mtcars.shape[0])

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [29]:
mtcars['vs'] = mtcars_copy['vs'].map({0:'vshaped', 1:'straight'})
mtcars.head(mtcars.shape[0])

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,vshaped,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,vshaped,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,straight,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,straight,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,vshaped,0,3,2
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,straight,0,3,1
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,vshaped,0,3,4
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,straight,0,4,2
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,straight,0,4,2
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,straight,0,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,straight,0,4,4
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,vshaped,0,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,vshaped,0,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,vshaped,0,3,3
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,vshaped,0,3,4
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,vshaped,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,vshaped,0,3,4
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,straight,1,4,1
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,straight,1,4,2
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,straight,1,4,1
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,straight,0,3,1
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,vshaped,0,3,2
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,vshaped,0,3,2
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,vshaped,0,3,4
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,vshaped,0,3,2
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,straight,1,4,1
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,vshaped,1,5,2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,straight,1,5,2
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,vshaped,1,5,4
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,vshaped,1,5,6
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,vshaped,1,5,8
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,straight,1,4,2

In [30]:
mtcars[mtcars['cyl']>5].sort_values('cyl', ascending=True)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,vshaped,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,vshaped,1,4,4
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,straight,0,3,1
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,straight,0,3,1
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,straight,0,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,straight,0,4,4
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,vshaped,1,5,6
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,vshaped,1,5,4
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,vshaped,0,3,2
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,vshaped,0,3,4
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,vshaped,0,3,2
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,vshaped,0,3,2
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,vshaped,0,3,4
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,vshaped,0,3,3
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,vshaped,0,3,4
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,vshaped,0,3,3
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,vshaped,0,3,3
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,vshaped,0,3,4
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,vshaped,0,3,2
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,vshaped,0,3,4
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,vshaped,1,5,8

In [32]:
mtcars['am'] = mtcars_copy['am'].map({0:'automatic', 1:'manual'})
mtcars

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,vshaped,manual,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,vshaped,manual,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,straight,manual,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,straight,automatic,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,vshaped,automatic,3,2
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,straight,automatic,3,1
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,vshaped,automatic,3,4
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,straight,automatic,4,2
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,straight,automatic,4,2
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,straight,automatic,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,straight,automatic,4,4
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,vshaped,automatic,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,vshaped,automatic,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,vshaped,automatic,3,3
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,vshaped,automatic,3,4
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,vshaped,automatic,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,vshaped,automatic,3,4
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,straight,manual,4,1
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,straight,manual,4,2
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,straight,manual,4,1
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,straight,automatic,3,1
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,vshaped,automatic,3,2
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,vshaped,automatic,3,2
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,vshaped,automatic,3,4
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,vshaped,automatic,3,2
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,straight,manual,4,1
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,vshaped,manual,5,2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,straight,manual,5,2
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,vshaped,manual,5,4
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,vshaped,manual,5,6
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,vshaped,manual,5,8
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,straight,manual,4,2

In [57]:
mtcars.dtypes

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs       object
am       object
gear      int64
carb      int64
dtype: object

In [62]:
# how many cars have gear=5, automatic am=0
mtcars[(mtcars['gear'] == 5) & (mtcars['am'] == 'automatic')]

Empty DataFrame
Columns: [mpg, cyl, disp, hp, drat, wt, qsec, vs, am, gear, carb]
Index: []

In [64]:
mtcars[(mtcars['gear'] >= 4) & (mtcars['am'] == 'automatic')]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Merc 240D,24.4,4,146.7,62,3.69,3.19,20.0,straight,automatic,4,2
Merc 230,22.8,4,140.8,95,3.92,3.15,22.9,straight,automatic,4,2
Merc 280,19.2,6,167.6,123,3.92,3.44,18.3,straight,automatic,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.44,18.9,straight,automatic,4,4

In [45]:
# shows mean horsepower per each cylinder
mtcars.pivot_table(values='hp', index='cyl', observed=False)

             hp
cyl
4     82.636364
6    122.285714
8    209.214286

In [49]:
mtcars.pivot_table(values='mpg', index=['gear', 'am'], observed=False, aggfunc=['sum', 'mean'])

                  sum       mean
                  mpg        mpg
gear am
3    automatic  241.6  16.106667
4    automatic   84.2  21.050000
     manual     210.2  26.275000
5    manual     106.9  21.380000

In [50]:
# reset index makes the table iterable
mtcars.pivot_table(values='mpg', index=['gear', 'am'], observed=False, aggfunc=['sum', 'mean']).reset_index()

  gear         am    sum       mean
                     mpg        mpg
0    3  automatic  241.6  16.106667
1    4  automatic   84.2  21.050000
2    4     manual  210.2  26.275000
3    5     manual  106.9  21.380000

In [65]:
# inserting data as a parameter, querying median mpg per gear
pd.pivot_table(data=mtcars, observed=False,
               index='gear',
               values='mpg',
               aggfunc='median'
              ).reset_index()

   gear   mpg
0     3  15.5
1     4  22.8
2     5  19.7

In [66]:
pd.pivot_table(data=mtcars, observed=False, index='gear', columns='am', values='mpg', aggfunc=['mean', 'max', 'min' ,'count','sum','std'] ).reset_index()

   gear       mean               max              min            count         \
am       automatic  manual automatic manual automatic manual automatic manual
0     3  16.106667     NaN      21.5    NaN      10.4    NaN      15.0    NaN
1     4  21.050000  26.275      24.4   33.9      17.8   21.0       4.0    8.0
2     5        NaN  21.380       NaN   30.4       NaN   15.0       NaN    5.0

         sum              std
am automatic manual automatic    manual
0      241.6    NaN  3.371618       NaN
1       84.2  210.2  3.069745  5.414465
2        NaN  106.9       NaN  6.658979